# Generated by Django 3.0.7 on 2021-02-03 11:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_chatgroup_chatgroupmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatgroup',
            name='member',
        ),
        migrations.AddField(
            model_name='chatgroup',
            name='member',
            field=models.ManyToManyField(related_name='chat_groups', to=settings.AUTH_USER_MODEL),
        ),
    ]
